Repository vakulenko10/fitApp-frontend, pull requests merged in 2025-04, with the labels that each got.

#28 Refactor(ui): replace react-modal with shadcn/ui dialog component
  package-lock.json
  package.json
  src/pages/Home/Home.jsx
Labels: refactor

#29 Refactor(state-management): migrate component state to redux store
  src/index.css
  src/pages/Home/Home.jsx
  src/redux/calorieSlice.js
  src/redux/store.js
Labels: refactor

#30 Refactor(ui): implement global layout improvements and responsive refinements
  src/components/navigation/Header.jsx
  src/index.css
  src/pages/About/ThemeDisplayed.jsx
  src/pages/CreateRecipe/CreateRecipe.jsx
  src/pages/FAQ/Faq.jsx
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: enhancement, refactor

#34 Validation
  package-lock.json
  package.json
  src/lib/mealplan.js
  src/pages/CreateRecipe/CreateRecipe.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileData.jsx
  src/pages/Signup/Signup.jsx
  src/validation/calorieFormSchema.js
  src/validation/profileFormSchema.js
  src/validation/recipeFormSchema.js
  src/validation/registration.js
Labels: enhancement, refactor, validation

#35 validation added to the profile page
  src/lib/profile.js
  src/pages/Profile/ProfileData.jsx
  src/pages/Profile/UserCharts.jsx
  src/validation/profileFormSchema.js
Labels: enhancement, refactor, validation

#36 uppdate text
  src/pages/FAQ/Faq.jsx
Labels: enhancement

#37 Development
  package-lock.json
  package.json
  src/lib/mealplan.js
  src/lib/profile.js
  src/pages/CreateRecipe/CreateRecipe.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/ProfileData.jsx
  src/pages/Profile/UserCharts.jsx
  src/pages/Signup/Signup.jsx
  src/validation/calorieFormSchema.js
  src/validation/profileFormSchema.js
  src/validation/recipeFormSchema.js
  src/validation/registration.js
Labels: enhancement, refactor, validation

#40 Pages/seo
  src/components/navigation/Header.jsx
  src/pages/CreateRecipe/CreateRecipe.jsx
  src/pages/FAQ/Faq.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Profile/LineChart.jsx
  src/pages/Profile/MealPlanHistory.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileData.jsx
  src/pages/Profile/UserCharts.jsx
  src/pages/Signup/Signup.jsx
Labels: enhancement, refactor

#45 Added Unit and Integration Tests for Home Page & Calorie Calculator
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/__mocks__/lib/Authentication.js
  src/__mocks__/lib/mealplan.js
  src/__mocks__/lib/mockUser.js
  src/__mocks__/lib/profile.js
  src/__mocks__/lib/utils.js
  src/components/navigation/Header.jsx
  src/lib/calorieIntake.js
  src/lib/calorieIntake.test.js
  src/pages/Home/Home.jsx
  src/pages/Home/Home.test.jsx
  src/pages/Profile/ProfileData.jsx
  src/setupTests.js
  src/testing/test-utils.jsx
  vite.config.js
Labels: testing

#46 Development
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/__mocks__/lib/Authentication.js
  src/__mocks__/lib/mealplan.js
  src/__mocks__/lib/mockUser.js
  src/__mocks__/lib/profile.js
  src/__mocks__/lib/utils.js
  src/components/navigation/Header.jsx
  src/lib/calorieIntake.js
  src/lib/calorieIntake.test.js
  src/pages/Home/Home.jsx
  src/pages/Home/Home.test.jsx
  src/pages/Profile/MealPlanHistory.jsx
  src/pages/Profile/ProfileData.jsx
  src/setupTests.js
  src/testing/test-utils.jsx
  vite.config.js
Labels: validation, testing

#47 feat: implement calorie data flow between Home and CreateRecipe pages
  src/lib/calorieIntake.js
  src/pages/CreateRecipe/CreateRecipe.jsx
  src/pages/Home/Home.jsx
  src/redux/calorieSlice.js
Labels: enhancement, refactor

#48 removed profileData state from profile page, now everything depends o…
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileData.jsx
Labels: enhancement, refactor

#49 removed about page from router
  src/components/navigation/Footer.jsx
  src/components/navigation/navigations.jsx
Labels: enhancement, refactor
